server:
  port: 8080
  base_url: "/api"

database:
  engine: "postgres"
  host: "localhost"
  port: 5432
  name: "gin_framework"
  user: "testadmin"
  password: "enigma"
  max_upload_size: 512 #500 Kb
  connection_timeout: 5


